### ISSUE TITLE
Implementing cost function in neurotune

### ISSUE THREAD

**Issue by travs** [vellamike/neurotune#4]
It seems like the cost function should be implemented in neurotune (perhaps in the `evaluator` class), but in the example given in the docs, the cost function is returned from somewhere in PyElectro.

@vellamike Is there a particular reason for implementing the cost function in pyElectro versus in neurotune itself? I am a bit unclear on where to put that function at the moment.

**Comment by pgleeson** [comment]
I agree. Will move it in my fork.

**Comment by pgleeson** [comment]
Moved in commits mentioned above.

**Comment by travs** [comment]
Great! :)
